# **Sensor Temperature Analysis**
---
You are given daily temperature readings from 4 weather stations, each with 5 daily readings:


In [1]:
# =======================
# Sensor Temperature Analysis - Summary
# =======================
import numpy as np

data = np.array([[22.5, 19.0, 31.2, 28.7, 25.1],
                 [17.3, 22.8, 30.5, 26.4, 21.9],
                 [33.1, 29.6, 18.4, 24.0, 27.8],
                 [20.2, 23.5, 31.9, 28.1, 22.6]])


In [29]:
# Task 1 Shape & Mean per Station
print("Task 1: Shape and Mean Temperature per Station")
print("-" * 30)
print("The Shape of data : ", data.shape)
print("-" * 30)
print("Mean temperature per station : " ,np.mean(data ,axis=1))
print("-" * 30)

Task 1: Shape and Mean Temperature per Station
------------------------------
The Shape of data :  (4, 5)
------------------------------
Mean temperature per station :  [25.3  23.78 26.58 25.26]
------------------------------


In [28]:
# Task 2 Using a boolean mask, extract all temperature readings above 28.0°C
# create boolean mask :
print("Task 2: Temperatures above 28°C")
print("-" * 30)
b_mask = data > 28.0
print("Boolean Mask :\n",b_mask)
print("-" * 30)

# Extract all temperature readings above 28.0°C
above_data = data[b_mask]

#print them as a 1D array.
print("Extracted values (1D array): : \n",above_data)
print("-" * 30)

Task 2: Temperatures above 28°C
------------------------------
Boolean Mask :
 [[False False  True  True False]
 [False False  True False False]
 [ True  True False False False]
 [False False  True  True False]]
------------------------------
Extracted values (1D array): : 
 [31.2 28.7 30.5 33.1 29.6 31.9 28.1]
------------------------------


In [33]:
# Task 3 Normalize the entire data array to the range [0, 1] using the formula below

# normalized = (data - data.min()) / (data.max() - data.min()
print("Task 3: Normalized Data (0-1) rounded to 2 decimals")
print("-" * 30)
data_normalized = (data - data.min()) / (data.max() - data.min())

# print the result rounded to 2 decimal places:
print("Normalized Data range [0, 1]  :\n\n",np.round(data_normalized,2))
print("-" * 30)

print("All tasks completed successfully ✅")

Task 3: Normalized Data (0-1) rounded to 2 decimals
------------------------------
Normalized Data range [0, 1]  :

 [[0.33 0.11 0.88 0.72 0.49]
 [0.   0.35 0.84 0.58 0.29]
 [1.   0.78 0.07 0.42 0.66]
 [0.18 0.39 0.92 0.68 0.34]]
------------------------------
All tasks completed successfully ✅
